# -*- coding: utf-8 -*-
"""Anomaly-Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBMks6WyNfPAx1-dkeYolfDuNWJg5GY8
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest

data = pd.read_csv("transaction_anomalies_dataset.csv")
print(data.head())

print(data.isnull().sum())

print(data.info())

print(data.describe())

data["Transaction_Amount"].hist()
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.show()

data["Frequency_of_Transactions"].hist()
plt.xlabel("Frequency of Transactions")
plt.ylabel("Frequency")
plt.show()

data["Average_Transaction_Amount"].hist()
plt.xlabel("Average Transaction Amount")
plt.ylabel("Frequency")
plt.show()

data.boxplot(by="Day_of_Week", column="Transaction_Amount")
plt.xlabel("Day of Week")
plt.ylabel("Transaction Amount")
plt.show()

data.boxplot(by="Time_of_Day", column="Transaction_Amount")
plt.xlabel("Time of Day")
plt.ylabel("Transaction Amount")
plt.show()

data.boxplot(by="Account_Type", column="Transaction_Amount")
plt.xlabel("Account Type")
plt.ylabel("Transaction Amount")
plt.show()

data["Transaction_Amount"].describe()
data["Frequency_of_Transactions"].describe()
data["Average_Transaction_Amount"].describe()

fig_box_amount = px.box(data,
                        x='Account_Type',
                        y='Transaction_Amount',
                        title='Transaction Amount by Account Type')
fig_box_amount.show()

fig_scatter_avg_amount_age = px.scatter(data, x='Age',
                                        y='Average_Transaction_Amount',
                                        color='Account_Type',
                                        title='Average Transaction Amount vs. Age',
                                        trendline='ols')
fig_scatter_avg_amount_age.show()

import seaborn as sns

numeric_data = data[["Transaction_Amount", "Frequency_of_Transactions", "Average_Transaction_Amount", "Income"]]
correlation_matrix = numeric_data.corr()

sns.heatmap(correlation_matrix, annot=True)
plt.show()

# Calculate mean and standard deviation of Transaction Amount
mean_amount = data['Transaction_Amount'].mean()
std_amount = data['Transaction_Amount'].std()

# Define the anomaly threshold (2 standard deviations from the mean)
anomaly_threshold = mean_amount + 2 * std_amount

# Flag anomalies
data['Is_Anomaly'] = data['Transaction_Amount'] > anomaly_threshold

# Scatter plot of Transaction Amount with anomalies highlighted
fig_anomalies = px.scatter(data, x='Transaction_Amount', y='Average_Transaction_Amount',
                           color='Is_Anomaly', title='Anomalies in Transaction Amount')
fig_anomalies.update_traces(marker=dict(size=12),
                            selector=dict(mode='markers', marker_size=1))
fig_anomalies.show()

# Calculate the number of anomalies
num_anomalies = data['Is_Anomaly'].sum()

# Calculate the total number of instances in the dataset
total_instances = data.shape[0]

# Calculate the ratio of anomalies
anomaly_ratio = num_anomalies / total_instances
print(anomaly_ratio)

relevant_features = ['Transaction_Amount',
                     'Average_Transaction_Amount',
                     'Frequency_of_Transactions']

# Split data into features (X) and target variable (y)
X = data[relevant_features]
y = data['Is_Anomaly']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Isolation Forest model
model = IsolationForest(contamination=0.02, random_state=42)
model.fit(X_train)

# Predict anomalies on the test set
y_pred = model.predict(X_test)

# Convert predictions to binary values (0: normal, 1: anomaly)
y_pred_binary = [1 if pred == -1 else 0 for pred in y_pred]

# Evaluate the model's performance
report = classification_report(y_test, y_pred_binary, target_names=['Normal', 'Anomaly'])
print(report)

# Relevant features used during training
relevant_features = ['Transaction_Amount', 'Average_Transaction_Amount', 'Frequency_of_Transactions']

# Get user inputs for features
user_inputs = []
for feature in relevant_features:
    user_input = float(input(f"Enter the value for '{feature}': "))
    user_inputs.append(user_input)

# Create a DataFrame from user inputs
user_df = pd.DataFrame([user_inputs], columns=relevant_features)

# Predict anomalies using the model
user_anomaly_pred = model.predict(user_df)

# Convert the prediction to binary value (0: normal, 1: anomaly)
user_anomaly_pred_binary = 1 if user_anomaly_pred == -1 else 0

if user_anomaly_pred_binary == 1:
    print("Anomaly detected: This transaction is flagged as an anomaly.")
else:
    print("No anomaly detected: This transaction is normal.")